engine: {}
containers:
  # added by compose::add
  math-worker:
    worker: path://./workers/math-worker
  # added by compose::add
  caller-worker:
    worker: path://./workers/caller-worker
  # added by compose::add
  state:
    worker: package://api.workers.iii.dev/state
    version: "0.22.2"
  # added by compose::add
  http:
    worker: package://api.workers.iii.dev/http
    version: "0.21.4"
